# Informazioni sul Sito
title: StoreGears
author: Oleksandr Bihansky
author_name: Oleksandr
brand: StoreGears
email: info@storegears.com
support_email: support@storegears.com

# URL e Link
url: "https://storegears.com"
baseurl: "" # Lascialo vuoto se il sito è nel dominio principale

# Impostazioni di Build
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# Per google search
plugins:
  - jekyll-sitemap

# Banner di Manutenzione, mettere su true durante la manutenzione, altrimenti su false
maintenance_mode: false